/**
 * Pre-build script: Validate JSON resources and generate PDFs before Astro build
 *
 * 1. Runs comprehensive JSON audit (schema, language, bilingual parity)
 * 2. Generates PDFs with smart caching (only when JSON changes)
 *
 * This runs automatically before `npm run build` to ensure
 * all content is validated and PDFs are up-to-date.
 */

import { execSync } from "child_process";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { statSync, existsSync } from "fs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, "..");

console.log("\n" + "=".repeat(80));
console.log("🔍 STEP 1: JSON Resource Audit");
console.log("=".repeat(80));

try {
  console.log("Running comprehensive JSON audit...\n");
  execSync("python scripts/audit-json-resources.py", {
    cwd: rootDir,
    stdio: "inherit",
  });
  console.log("\n✅ JSON audit passed!\n");
} catch (error) {
  console.error("\n❌ JSON audit failed!");
  console.error("Fix the issues above before building.");
  process.exit(1);
}

console.log("=".repeat(80));
console.log("📄 STEP 2: PDF Generation");
console.log("=".repeat(80) + "\n");

// Define your PDF resources here
// Note: Using unified PDF generator (generate-all-pdfs.py) instead of individual scripts
const pdfResources = [
  // All PDFs are now generated by the unified script
  // Run manually: python scripts/generate-all-pdfs.py
];

/**
 * Check if PDF needs regeneration
 * Returns true if JSON is newer than PDF or PDF doesn't exist
 */
function needsRegeneration(jsonPath, pdfPath) {
  const fullJsonPath = join(rootDir, jsonPath);
  const fullPdfPath = join(rootDir, pdfPath);

  // If PDF doesn't exist, regenerate
  if (!existsSync(fullPdfPath)) {
    return true;
  }

  // If JSON doesn't exist, skip (error will be caught later)
  if (!existsSync(fullJsonPath)) {
    return false;
  }

  // Compare modification times
  const jsonMtime = statSync(fullJsonPath).mtime.getTime();
  const pdfMtime = statSync(fullPdfPath).mtime.getTime();

  return jsonMtime > pdfMtime;
}

console.log("🔄 Checking PDFs for updates...\n");

let generated = 0;
let skipped = 0;
let failed = 0;

for (const resource of pdfResources) {
  try {
    if (needsRegeneration(resource.jsonPath, resource.pdfPath)) {
      console.log(`📝 Generating: ${resource.name}`);
      execSync(resource.script, {
        cwd: rootDir,
        stdio: "inherit",
      });
      generated++;
    } else {
      console.log(`⏭️  Skipped: ${resource.name} (up to date)`);
      skipped++;
    }
  } catch (error) {
    console.error(`\n❌ Failed to generate: ${resource.name}`);
    console.error(`   Error: ${error.message}`);
    failed++;
    // Continue with other resources
  }
}

console.log("\n" + "=".repeat(80));
console.log("📊 PDF Generation Summary:");
console.log(`   ✅ Generated: ${generated}`);
console.log(`   ⏭️  Skipped: ${skipped} (already up to date)`);
if (failed > 0) {
  console.log(`   ❌ Failed: ${failed}`);
}
console.log("=".repeat(80));

if (failed > 0) {
  console.warn(
    "\n⚠️  Some PDFs failed to generate. Build will continue, but PDFs may be outdated.",
  );
} else if (generated === 0 && skipped > 0) {
  console.log("\n✅ All PDFs are up to date!");
} else {
  console.log("\n✅ PDF generation complete!");
}
